### ISSUE TITLE
Not a issue :-)

### ISSUE THREAD

**Issue by W73** [nicolas-r/katello-centos-errata-import#5]
When using katello-centos-errata-import with python2 i found, that there already exists katello module in 
katello-host-tools-3.3.5-3.el7.noarch and resides in /usr/lib/python2.7/site-packages/katello/ 
So i had to rename modules/katello to modules/katelloerrata

**Comment by nicolas-r** [comment]
Hi

thanks for this report, I will see how what I will deal with it
